/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardApprovalQueueRouteImport } from './routes/dashboard/approval-queue'
import { Route as DashboardExecutiveRouteImport } from './routes/dashboard/executive'
import { Route as DashboardInventoryRouteImport } from './routes/dashboard/inventory'
import { Route as DashboardSpvRouteImport } from './routes/dashboard/spv'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardApprovalQueueRoute = DashboardApprovalQueueRouteImport.update({
  id: '/dashboard/approval-queue',
  path: '/dashboard/approval-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardExecutiveRoute = DashboardExecutiveRouteImport.update({
  id: '/dashboard/executive',
  path: '/dashboard/executive',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardInventoryRoute = DashboardInventoryRouteImport.update({
  id: '/dashboard/inventory',
  path: '/dashboard/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSpvRoute = DashboardSpvRouteImport.update({
  id: '/dashboard/spv',
  path: '/dashboard/spv',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/dashboard/approval-queue': typeof DashboardApprovalQueueRoute
  '/dashboard/executive': typeof DashboardExecutiveRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/spv': typeof DashboardSpvRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/dashboard/approval-queue': typeof DashboardApprovalQueueRoute
  '/dashboard/executive': typeof DashboardExecutiveRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/spv': typeof DashboardSpvRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/dashboard/approval-queue': typeof DashboardApprovalQueueRoute
  '/dashboard/executive': typeof DashboardExecutiveRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/spv': typeof DashboardSpvRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/login'
    | '/dashboard/approval-queue'
    | '/dashboard/executive'
    | '/dashboard/inventory'
    | '/dashboard/spv'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/login'
    | '/dashboard/approval-queue'
    | '/dashboard/executive'
    | '/dashboard/inventory'
    | '/dashboard/spv'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/change-password'
    | '/login'
    | '/dashboard/approval-queue'
    | '/dashboard/executive'
    | '/dashboard/inventory'
    | '/dashboard/spv'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  LoginRoute: typeof LoginRoute
  DashboardApprovalQueueRoute: typeof DashboardApprovalQueueRoute
  DashboardExecutiveRoute: typeof DashboardExecutiveRoute
  DashboardInventoryRoute: typeof DashboardInventoryRoute
  DashboardSpvRoute: typeof DashboardSpvRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/approval-queue': {
      id: '/dashboard/approval-queue'
      path: '/dashboard/approval-queue'
      fullPath: '/dashboard/approval-queue'
      preLoaderRoute: typeof DashboardApprovalQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/executive': {
      id: '/dashboard/executive'
      path: '/dashboard/executive'
      fullPath: '/dashboard/executive'
      preLoaderRoute: typeof DashboardExecutiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/inventory': {
      id: '/dashboard/inventory'
      path: '/dashboard/inventory'
      fullPath: '/dashboard/inventory'
      preLoaderRoute: typeof DashboardInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/spv': {
      id: '/dashboard/spv'
      path: '/dashboard/spv'
      fullPath: '/dashboard/spv'
      preLoaderRoute: typeof DashboardSpvRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  LoginRoute: LoginRoute,
  DashboardApprovalQueueRoute: DashboardApprovalQueueRoute,
  DashboardExecutiveRoute: DashboardExecutiveRoute,
  DashboardInventoryRoute: DashboardInventoryRoute,
  DashboardSpvRoute: DashboardSpvRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
